import { User, Conversation, MoodEntry, Mood, UserMemory, Recommendation } from './types'

export const mockUser: User = {
  id: 'user-001',
  name: 'Adaeze Okonkwo',
  email: 'adaeze.okonkwo@email.com',
  specialisation: 'Work & Career Stress',
  languageProfile: 'nigerian-english',
  createdAt: '2024-11-01T09:00:00Z',
}

export const mockConversations: Conversation[] = [
  {
    id: 'conv-001',
    userId: 'user-001',
    title: 'Monday wahala at work',
    mode: 'text',
    createdAt: '2024-12-02T08:30:00Z',
    messages: [
      {
        id: 'msg-001',
        conversationId: 'conv-001',
        sender: 'user',
        content: 'I don tire for this job o. My oga just dumped three projects on me without even asking if I have capacity. The deadline is tomorrow!',
        adaptiveMode: 'listening',
        timestamp: '2024-12-02T08:30:00Z',
      },
      {
        id: 'msg-002',
        conversationId: 'conv-001',
        sender: 'ai',
        content: 'Hmm, that sounds really frustrating — carrying three projects at once with a tomorrow deadline is genuinely a lot to handle. You have every right to feel overwhelmed right now. Tell me, wetin dey worry you most about this situation: the workload itself, or how your oga is treating you?',
        adaptiveMode: 'listening',
        timestamp: '2024-12-02T08:31:15Z',
      },
      {
        id: 'msg-003',
        conversationId: 'conv-001',
        sender: 'user',
        content: 'Both honestly. I feel like I am invisible in that office. Nobody ever asks how I am managing before piling more work.',
        adaptiveMode: 'listening',
        timestamp: '2024-12-02T08:33:00Z',
      },
      {
        id: 'msg-004',
        conversationId: 'conv-001',
        sender: 'ai',
        content: 'That feeling of being invisible — like your limits don\'t matter — is one of the heaviest things to carry in a workplace. It is not just about the tasks; it is about not feeling seen as a full human being. Have you ever had a chance to say something to your oga about how this affects you, even once?',
        adaptiveMode: 'listening',
        timestamp: '2024-12-02T08:34:30Z',
      },
      {
        id: 'msg-005',
        conversationId: 'conv-001',
        sender: 'user',
        content: 'No, I am scared. He has a way of making you feel like you are being lazy if you push back.',
        adaptiveMode: 'coach',
        timestamp: '2024-12-02T08:36:00Z',
      },
      {
        id: 'msg-006',
        conversationId: 'conv-001',
        sender: 'ai',
        content: 'That fear is valid — Nigerian work culture can really punish boundaries, especially from junior staff. But here\'s a small thing to consider: you don\'t have to confront him directly. Sometimes a calm "I want to make sure I deliver well — can we talk about priorities?" puts you in control without sounding difficult. Would you like to practice how that conversation might go?',
        adaptiveMode: 'coach',
        timestamp: '2024-12-02T08:37:45Z',
      },
    ],
  },
  {
    id: 'conv-002',
    userId: 'user-001',
    title: 'Anxiety about family pressure',
    mode: 'text',
    createdAt: '2024-12-04T20:10:00Z',
    messages: [
      {
        id: 'msg-007',
        conversationId: 'conv-002',
        sender: 'user',
        content: 'My family keeps asking when I will marry. I am 29 and they act like I am already expired.',
        adaptiveMode: 'listening',
        timestamp: '2024-12-04T20:10:00Z',
      },
      {
        id: 'msg-008',
        conversationId: 'conv-002',
        sender: 'ai',
        content: 'Twenty-nine and "expired" — omo, the pressure we put on people in this country! That language alone must sting, especially when it comes from your own family. How does it feel when they bring it up — is it mostly embarrassment, or is there some part of you that is also genuinely worried?',
        adaptiveMode: 'listening',
        timestamp: '2024-12-04T20:11:30Z',
      },
      {
        id: 'msg-009',
        conversationId: 'conv-002',
        sender: 'user',
        content: 'Honestly? Both. I want to get married someday but not because of pressure. And I also feel like something is wrong with me.',
        adaptiveMode: 'care',
        timestamp: '2024-12-04T20:13:00Z',
      },
      {
        id: 'msg-010',
        conversationId: 'conv-002',
        sender: 'ai',
        content: 'Nothing is wrong with you — nothing at all. Wanting something on your own terms is not a defect, it is wisdom. The pain is real though: when the people who are supposed to be your safe place become a source of shame, it cuts deep. I hear you. Can I ask — outside of marriage, how are other parts of your life feeling right now?',
        adaptiveMode: 'care',
        timestamp: '2024-12-04T20:14:45Z',
      },
      {
        id: 'msg-011',
        conversationId: 'conv-002',
        sender: 'user',
        content: 'Work is stressful, friendships have been distant, but I am managing. Just feel lonely sometimes.',
        adaptiveMode: 'companion',
        timestamp: '2024-12-04T20:16:00Z',
      },
    ],
  },
  {
    id: 'conv-003',
    userId: 'user-001',
    title: 'Exploring mindfulness for sleep',
    mode: 'text',
    createdAt: '2024-12-06T22:00:00Z',
    messages: [
      {
        id: 'msg-012',
        conversationId: 'conv-003',
        sender: 'user',
        content: 'I cannot sleep again. My brain just dey run at night.',
        adaptiveMode: 'explorer',
        timestamp: '2024-12-06T22:00:00Z',
      },
      {
        id: 'msg-013',
        conversationId: 'conv-003',
        sender: 'ai',
        content: 'A racing mind at night — I know that feeling is exhausting. Before we explore what might help, let me ask: is it mostly thoughts about tomorrow, replaying today, or more random anxiety that kicks in?',
        adaptiveMode: 'explorer',
        timestamp: '2024-12-06T22:01:15Z',
      },
      {
        id: 'msg-014',
        conversationId: 'conv-003',
        sender: 'user',
        content: 'Tomorrow mostly. I start planning everything and cannot stop.',
        adaptiveMode: 'explorer',
        timestamp: '2024-12-06T22:02:30Z',
      },
      {
        id: 'msg-015',
        conversationId: 'conv-003',
        sender: 'ai',
        content: 'That is actually useful to know — your brain is trying to protect you by preparing, but it has not learned when to switch off. There is a technique called a "worry dump": before bed, write down everything you need to do tomorrow in a list, then close the notebook and tell yourself "it is handled." The brain stops looping because it trusts the list. Want to try it tonight?',
        adaptiveMode: 'coach',
        timestamp: '2024-12-06T22:04:00Z',
      },
      {
        id: 'msg-016',
        conversationId: 'conv-003',
        sender: 'user',
        content: 'That actually sounds doable. I never tried that before.',
        adaptiveMode: 'coach',
        timestamp: '2024-12-06T22:05:30Z',
      },
      {
        id: 'msg-017',
        conversationId: 'conv-003',
        sender: 'ai',
        content: 'Yes! And if you want to go further, pair it with 4-7-8 breathing: inhale for 4 counts, hold for 7, exhale for 8. It activates your parasympathetic nervous system — basically tells your body "we are safe now, we can rest." Try both tonight and let me know how it goes.',
        adaptiveMode: 'coach',
        timestamp: '2024-12-06T22:06:45Z',
      },
    ],
  },
]

export const mockMoodEntries: MoodEntry[] = [
  {
    id: 'mood-001',
    userId: 'user-001',
    mood: Mood.Anxious,
    triggerTag: 'work',
    note: 'Big presentation today, stomach tight all morning',
    date: '2024-12-01',
  },
  {
    id: 'mood-002',
    userId: 'user-001',
    mood: Mood.Overwhelmed,
    triggerTag: 'work',
    note: 'Three deadlines dropped on me at once. E don do.',
    date: '2024-12-02',
  },
  {
    id: 'mood-003',
    userId: 'user-001',
    mood: Mood.Sad,
    triggerTag: 'family',
    note: 'Mum called again about marriage. I just kept quiet.',
    date: '2024-12-03',
  },
  {
    id: 'mood-004',
    userId: 'user-001',
    mood: Mood.Calm,
    triggerTag: 'self',
    note: 'Took a walk in the evening. No phones, no news. Felt good.',
    date: '2024-12-04',
  },
  {
    id: 'mood-005',
    userId: 'user-001',
    mood: Mood.Happy,
    triggerTag: 'social',
    note: 'Video call with my friends from uni. Laughed plenty.',
    date: '2024-12-05',
  },
  {
    id: 'mood-006',
    userId: 'user-001',
    mood: Mood.Anxious,
    triggerTag: 'sleep',
    note: 'Could not sleep until 2am. Brain would not cooperate.',
    date: '2024-12-06',
  },
  {
    id: 'mood-007',
    userId: 'user-001',
    mood: Mood.Calm,
    triggerTag: 'self',
    note: 'Tried the worry dump + breathing technique. Actually slept by midnight!',
    date: '2024-12-07',
  },
]

export const mockUserMemories: UserMemory[] = [
  {
    id: 'mem-001',
    userId: 'user-001',
    memoryType: 'trigger',
    content: 'Work deadlines, especially last-minute ones from her manager, consistently trigger anxiety and feelings of invisibility.',
    confidenceScore: 0.92,
    source: 'conv-001',
  },
  {
    id: 'mem-002',
    userId: 'user-001',
    memoryType: 'trigger',
    content: 'Family pressure around marriage causes a mix of shame and self-doubt, particularly phone calls from her mother.',
    confidenceScore: 0.88,
    source: 'conv-002',
  },
  {
    id: 'mem-003',
    userId: 'user-001',
    memoryType: 'pattern',
    content: 'She tends to internalise workplace stress rather than verbalise it to authority figures, driven by fear of being labeled lazy.',
    confidenceScore: 0.85,
    source: 'conv-001',
  },
  {
    id: 'mem-004',
    userId: 'user-001',
    memoryType: 'resilience',
    content: 'Responds well to practical, step-by-step coping tools (e.g., worry dump, breathing techniques) once she decides to try them.',
    confidenceScore: 0.90,
    source: 'conv-003',
  },
  {
    id: 'mem-005',
    userId: 'user-001',
    memoryType: 'vocabulary',
    content: 'Uses Nigerian English naturally: "wahala" (trouble), "oga" (boss/sir), "e don do" (it is too much / I am done). Responds positively when AI mirrors this.',
    confidenceScore: 0.95,
    source: 'conv-001',
  },
]

export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec-001',
    icon: '🧘',
    text: 'Try a 5-minute body scan tonight before bed — it can calm the racing thoughts you mentioned.',
    category: 'mindfulness',
  },
  {
    id: 'rec-002',
    icon: '📝',
    text: 'Write down three things that went okay today, no matter how small. Your brain needs evidence of good.',
    category: 'self-care',
  },
  {
    id: 'rec-003',
    icon: '🚶',
    text: 'A 15-minute walk without your phone can lower cortisol by up to 20%. Your Wednesday walk really helped!',
    category: 'physical',
  },
]
